sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t trinhno/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true trinhno/react-test npm test

after_success:
  - docker build -t trinhno/complex-client ./client
  - docker build -t trinhno/complex-server ./server
  - docker build -t trinhno/complex-worker ./worker
  - docker build -t trinhno/complex-nginx ./nginx
  # Login to Docker Hub
  - echo $DOCKER_PASSWORD | docker login -u trinhno --password-stdin
  # Push images to Docker Hub
  - docker push trinhno/complex-client
  - docker push trinhno/complex-server
  - docker push trinhno/complex-worker
  - docker push trinhno/complex-nginx 

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'complex-docker'
  env: 'Complexdocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-285763974571'
  bucket_path: 'complex-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
